// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "TaskPM Support"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/workers": {
            "get": {
                "description": "获取所有已注册的 Worker 配置列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "获取 Worker 列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkerListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的 Worker 或更新已存在的 Worker 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "创建或更新 Worker",
                "parameters": [
                    {
                        "description": "Worker 配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateWorkerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workers/register": {
            "post": {
                "description": "Worker SDK 自动注册接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "注册 Worker",
                "parameters": [
                    {
                        "description": "Worker 注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterWorkerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workers/{worker_name}": {
            "get": {
                "description": "根据 worker_name 获取 Worker 配置详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "获取 Worker 详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker 名称",
                        "name": "worker_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workers/{worker_name}/heartbeat": {
            "post": {
                "description": "更新指定 Worker 的心跳时间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "更新 Worker 心跳",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker 名称",
                        "name": "worker_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HeartbeatResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workers/{worker_name}/stats": {
            "get": {
                "description": "获取指定 Worker 的任务统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "获取 Worker 统计信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker 名称",
                        "name": "worker_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkerStatsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workers/{worker_name}/timeseries": {
            "get": {
                "description": "获取指定 Worker 的时间序列统计数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workers"
                ],
                "summary": "获取 Worker 时间序列统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker 名称",
                        "name": "worker_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "统计小时数",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkerTimeSeriesResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "服务存活检查，用于 Kubernetes liveness probe",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness 检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.CheckResult"
                        }
                    }
                }
            }
        },
        "/queues/clear": {
            "post": {
                "description": "清空指定 Worker 的队列（删除所有待处理任务）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Queues"
                ],
                "summary": "清空队列",
                "parameters": [
                    {
                        "description": "清空队列请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClearQueueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ClearQueueResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/clear-dead": {
            "post": {
                "description": "清空指定 Worker 的死信队列（已达最大重试次数的失败任务）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Queues"
                ],
                "summary": "清空死信队列",
                "parameters": [
                    {
                        "description": "清空死信队列请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClearDeadQueueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ClearDeadQueueResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/queues/stats": {
            "get": {
                "description": "获取指定 Worker 的所有队列状态统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Queues"
                ],
                "summary": "查询队列状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker 名称",
                        "name": "worker_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.QueueStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "服务就绪检查，检查依赖服务（PostgreSQL、Redis）状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness 检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.CheckResult"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.CheckResult"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "分页查询任务列表，支持多条件过滤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "查询任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker 名称",
                        "name": "worker_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "队列名称",
                        "name": "queue",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TaskListResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的异步任务并入队到 Asynq",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "任务创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/batch-retry": {
            "post": {
                "description": "批量重试指定条件的失败任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "批量重试失败任务",
                "parameters": [
                    {
                        "description": "重试条件",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BatchRetryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BatchRetryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}": {
            "get": {
                "description": "根据 task_id 获取任务详细信息及执行历史",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "获取任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TaskResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}/replay": {
            "post": {
                "description": "将已完成或失败的任务重新入队执行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "重放任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "重放参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.ReplayTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReplayTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}/report-attempt": {
            "post": {
                "description": "Worker 上报任务执行的详细状态（running、success、fail）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "上报任务执行状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "执行状态",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReportAttemptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BatchRetryRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 100
                },
                "status": {
                    "type": "string",
                    "example": "fail"
                },
                "task_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.BatchRetryResponse": {
            "type": "object",
            "properties": {
                "new_task_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "total_retried": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "dto.ClearDeadQueueRequest": {
            "type": "object",
            "required": [
                "worker_name"
            ],
            "properties": {
                "queue_name": {
                    "type": "string",
                    "example": "default"
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.ClearDeadQueueResponse": {
            "type": "object",
            "properties": {
                "cleared_queues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "total_deleted": {
                    "type": "integer",
                    "example": 50
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.ClearQueueRequest": {
            "type": "object",
            "required": [
                "worker_name"
            ],
            "properties": {
                "queue_name": {
                    "type": "string",
                    "example": "default"
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.ClearQueueResponse": {
            "type": "object",
            "properties": {
                "cleared_queues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "total_deleted": {
                    "type": "integer",
                    "example": 100
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.CreateTaskRequest": {
            "type": "object"
        },
        "dto.CreateTaskResponse": {
            "type": "object",
            "properties": {
                "asynq_task_id": {
                    "type": "string"
                },
                "queue": {
                    "type": "string",
                    "example": "default"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "task_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.CreateWorkerRequest": {
            "type": "object",
            "required": [
                "concurrency",
                "queues",
                "worker_name"
            ],
            "properties": {
                "base_url": {
                    "type": "string",
                    "example": "http://localhost:8080"
                },
                "concurrency": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 10
                },
                "default_delay": {
                    "type": "integer",
                    "example": 0
                },
                "default_retry_count": {
                    "type": "integer",
                    "example": 3
                },
                "default_timeout": {
                    "type": "integer",
                    "example": 30
                },
                "queues": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "redis_addr": {
                    "type": "string",
                    "example": "redis://localhost:6379/0"
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "错误信息"
                }
            }
        },
        "dto.HeartbeatResponse": {
            "type": "object",
            "properties": {
                "heartbeat_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.QueueStatsResponse": {
            "type": "object",
            "properties": {
                "queues": {
                    "type": "array",
                    "items": {}
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.RegisterWorkerRequest": {
            "type": "object",
            "required": [
                "concurrency",
                "queues",
                "worker_name"
            ],
            "properties": {
                "base_url": {
                    "type": "string",
                    "example": "http://localhost:8080"
                },
                "concurrency": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 10
                },
                "default_delay": {
                    "type": "integer",
                    "example": 0
                },
                "default_retry_count": {
                    "type": "integer",
                    "example": 3
                },
                "default_timeout": {
                    "type": "integer",
                    "example": 30
                },
                "queues": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "redis_addr": {
                    "type": "string",
                    "example": "redis://localhost:6379/0"
                },
                "worker_name": {
                    "type": "string",
                    "example": "my-worker"
                }
            }
        },
        "dto.ReplayTaskRequest": {
            "type": "object",
            "properties": {
                "delay": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.ReplayTaskResponse": {
            "type": "object",
            "properties": {
                "new_task_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "dto.ReportAttemptRequest": {
            "type": "object"
        },
        "dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "dto.TaskListResponse": {
            "type": "object",
            "properties": {
                "items": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.TaskResponse": {
            "type": "object",
            "properties": {
                "task": {}
            }
        },
        "dto.WorkerListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workers.Config"
                    }
                }
            }
        },
        "dto.WorkerResponse": {
            "type": "object",
            "properties": {
                "worker": {
                    "$ref": "#/definitions/workers.Config"
                }
            }
        },
        "dto.WorkerStatsResponse": {
            "type": "object",
            "properties": {
                "stats": {}
            }
        },
        "dto.WorkerTimeSeriesResponse": {
            "type": "object",
            "properties": {
                "timeseries": {}
            }
        },
        "healthcheck.CheckResult": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "\"ok\" or \"error\"",
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "workers.Config": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "concurrency": {
                    "type": "integer"
                },
                "default_delay": {
                    "description": "seconds",
                    "type": "integer"
                },
                "default_retry_count": {
                    "type": "integer"
                },
                "default_timeout": {
                    "description": "seconds",
                    "type": "integer"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "last_heartbeat_at": {
                    "type": "string"
                },
                "queues": {
                    "description": "queue_name -\u003e weight",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "redis_addr": {
                    "type": "string"
                },
                "worker_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:28080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "TaskPM API",
	Description:      "分布式任务管理系统 - 基于 Asynq 和 PostgreSQL 的任务调度平台",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
